### ISSUE TITLE
Add JMH-based tests for JDBC

### ISSUE THREAD

**Issue by vlsi** [eclipse-vertx/vertx-sql-client#144]
Alternative option would be to add reactive tests to https://github.com/pgjdbc/benchmarks.

**Comment by vietj** [comment]
interesting, thanks!

**Comment by vietj** [comment]
we do have a couple of benchmarks in this project, but that's more to have a rough idea of how it performs, ideally we should have a benchmark with a mock server which would help define latencies on the mock server and compare performance corresponding to the mocked latencies

**Comment by vietj** [comment]
also a mock server wouldn't consume much CPU and would provide more accurate results

**Comment by vlsi** [comment]
Note: JMH is GPL licensed, so I'm not sure if a project can use JMH and use Apache license.

I'm not a lawyer, yet that was the reason JMH tests were put to a separate repository in pgjdbc project.

**Comment by vlsi** [comment]
Mock server is completely different beast, and a mock server could even simplify unit/integartion testing. It would be a great thing to do, yet it would be a non-trivial thing either.

**Comment by davecramer** [comment]
Somewhat related. I ran the benchmark https://github.com/reactiverse/reactive-pg-client/blob/master/src/benchmark/java/io/reactiverse/pgclient/RawBenchmark.java the JDBC driver performs slightly better in these benchmarks. Is that your expectation ?

**Comment by vietj** [comment]
@davecramer you are right, synchronous single threaded IO is faster than non blocking IO

if you want to see performance improvement then you can run the same benchmark with these settings

- have a database on a different host with some latency (a few millis)
- use reactive-pg pipelining

if you are using docker, you can use the docker image provided by this project (in /docker) that builds an image that provides the `tc` tool to add artificial latency.

what you can expect is, the highest the latency is, the better this client will perform.

The Techempower Framework Benchmark is an illustration of this, you can see that the cloud results provides better result than the bare machine, because (I suspect) the latency in cloud is a slightly higher.
