### ISSUE TITLE
Standalone Client always only uses 1 vertx thread, despite eventLoopPoolSize setting

### ISSUE THREAD

**Issue by ikitommi** [eclipse-vertx/vertx-sql-client#349]
Hi,

I'm using the client without Verx, big thanks for it. Is there a guide on setting the internal Vertx thread pool settings together with the db pool settings? e.g. if I use 64 as pool size, should the internal Vertx thread pool also be 64 or are the defaults always ok?

**Comment by vietj** [comment]
the internal vertx thread pool does not really matter in practice (threads are lazily created), and if you want to control it, a single event loop thread can achieve a lot of IO

**Comment by ikitommi** [comment]
Thanks!

**Comment by ikitommi** [comment]
I'm running the PgPool under Undertow, and calling the client from UnderTows IO Threads. There are the default 2*CPU IO Threads in Undertow, but the Vertx spins only just 1 `vert.x-eventloop-thread` handling the database connections, despite the load. The `Vertx` instance should have the 2*CPU and set the PgPool to same thread count. Do I need to initialize/deploy the underlaying Vertx somehow so it would start to use all the threads?

For small load, the 1 thread does ok, but running it under heavy (TFB) load, this is a bottleneck.

**Comment by ikitommi** [comment]
Making the pool ThreadLocal, I get 1 vert.x event thread per Undertow IO thread, but there are now also extra theads, so would like to have just one big vert.x pool to talk to.

<img width="1084" alt="Screenshot 2019-07-19 at 9 52 16" src="https://user-images.githubusercontent.com/567532/61515389-2abe7d80-aa0b-11e9-8458-c6ac54c6383f.png">

**Comment by BillyYccc** [comment]
Hi, you can create your own `Vertx` instance and manage it yourself, and you're able to configure the eventloop size with `VertxOptions#setEventLoopPoolSize` when instantiating the `Vertx` instance.

**Comment by vietj** [comment]
maybe in standalone mode (where vertx is instantiated by the client) we should use smaller event loop size ?

**Comment by ikitommi** [comment]
`Vertx` should already have more threads, tested and setting that manually doesn't change the fact that all calls on the `.preparedStatement` just use the one thread. Creating the `Vertx` just seems to spin just the `vert.x-blocked-thread-checker`. First call to the client puts out 1 thread, which is used for all future calls, despite the load.

Vertx samples seem to do:

```java
    vertx.deployVerticle(App.class.getName(),
        new DeploymentOptions().setInstances(POOL_SIZE).setConfig(config), event -> {
          if (event.succeeded()) {
            logger.info("Server listening on port " + 8080);
          } else {
            logger.error("Unable to start your application", event.cause());
          }
        });
```

, so should I instantiate a verticle out of my client so that it would be backed by the `POOL_SIZE` of vertx threads?

**Comment by ikitommi** [comment]
Renamed the issue. Would be interested in seeing how to run the client using the whole vertx pool.

**Comment by vietj** [comment]
what you can do is create several pools put them in a list and round robin on them when you need a connection

**Comment by vietj** [comment]
that being said, we are going soon to define more properly the notion of "shared" pool accross vertx (same need for other client) and we should take this in account.

**Comment by ikitommi** [comment]
Thanks for the answers. Looking forward to the shared pooling.

**Comment by Globegitter** [comment]
Has there been any progress on "shared" pools? Just running into the same scenario.

**Comment by vietj** [comment]
@Globegitter not yet, for the moment you should start several pools with different context and use a round robin selection on the pools

**Comment by niwinz** [comment]
Also: seems like the query result callback is executed in the context pg pool context (not calling context). So if you executing some additional code, this code will be executed in the same single thread blocking execution of other possible queries. (In fact, right now pgpool is single threaded... but if you forgot use `.runOnContext` just after query result, this will propagate the single threading to all application logic executed after query....)

The workaround for this is use `.runOnContext` just after query callback handler is resolved and switch back to the request context...

I think this issue is pretty important because having a single thread for execute queryes can become easy bottleneck in production applications. I think that the logical approach would be that the query is executed in the current request context, with this approach it each query will be executed in the same thread as request (and everything will work as expected when verticle has more than one instance).

**Comment by niwinz** [comment]
Aside, i'm using the `PgPool` with the verticles (not standalone) and it behaves identically: always using one single thread for execute all the queries (and the query callback is executed in the same thread as noted in previous my response) when I have the eventloop pool with 4 threads and 4 verticles deployed... 

I have thought that this issue is only when PgPool is used in a standalone mode... but this is also happens in verticles (or i'm doing something very wrong...).

**Comment by niwinz** [comment]
Testing with 4.0.0-milestone4, seems like running in verticles this issue is fixed. Just updating the app now starts using all the eventloop threads and the response callback is executed in the same calling context. :+1: 

Don't know if in standalone mode is fixed.

**Comment by vietj** [comment]
update : the 4.1 pool will try to reuse the event loop from the incoming vertx thread, if that's a non vertx thread then it would be the current event loop associated with this thread (now there is a concept of sticky context).

**Comment by vietj** [comment]
I think in standalone mode we could indeed do differently and use all event loops, this requires like an event loop selector I think or this kind of trick.

**Comment by vietj** [comment]
see https://github.com/eclipse-vertx/vertx-sql-client/issues/1095
