### ISSUE TITLE
allow SqlConnection::begin to take a handler as last argument

### ISSUE THREAD

**Issue by pmlopes** [eclipse-vertx/vertx-sql-client#421]
I'm working on implementing a JDBC implementation of this project, however the way transactions work on JDBC is by switching the `autoCommit` flag on the connection or setting the `transactionIsolationLevel`. Several drivers (such as the mysql one) will perform blocking IO operations at this time by sending the message:

```
SET autocommit=0
```

If this method `begin` would accept to be asynchronous, this would be simpler to handle on my side instead of having to buffers this command until a next one is invoked and then issue the `SET` and the user desired command, and send the error handling to the right place, etc...

Unless anyone thinks this is a bad idea, I'd like to hear from you guys @vietj @BillyYccc.

**Comment by BillyYccc** [comment]
+1 for what Paulo proposed here.

I think we should make the start transaction API less opinionated, we have clearly many benefits here.
* First it would be easier for the implementations based on our `vertx-sql-client` just like what's described above

* It would also be more straightforward for the upper frameworks/libraries(such as an ORM or something else...) to get things right, because sending a `BEGIN` SQL may change the state of the session, take `MySQL` for an instance, `BEGIN` will cause an implicit commit(see https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html), we have some magic in the current API and that may bring some unexpected behaviors for the users

* For application users I don't think `begin(Handler<AsyncResult<Transaction>> handler)` would be a problem for them compared to `begin()`

In fact this topic was discussed in https://github.com/eclipse-vertx/vertx-sql-client/issues/112 before.

**Comment by vietj** [comment]
I think changing the Transaction would sacrifice the usability of the API for the convenience of JDBC. Is it really complicated to achieve it with lazy transaction set ? it looks like a boolean to set and do some action when this boolean is set.

**Comment by vietj** [comment]
The 2nd point given by @BillyYccc looks more valid than the API implementation detail. So we should make a thorough analysis of what the current design is a blocker for.

Can you elaborate more @BillyYccc about the second point ?

**Comment by BillyYccc** [comment]
Let's start with a concrete example with MySQL here, with MySQL innoDB engine everything is running within a transaction

```
conn.query("SET autocommit = 0", ar -> {
    // autocommit mode is disabled
    conn.query(query01, ar2 -> {
        // query01 is not commited now
        Transaction tx = conn.begin(); // lazy begin send here
        // we can not know when query01 is committed because begin will cause an implicit commit but we have no track of it
        tx.query(query02, ar3 -> {
            // this may bring some unexpected behaviors
        });
    });
});
```

if we're using asynchronous transaction start 
```
conn.query("SET autocommit = 0", ar -> {
    // autocommit mode is disabled
    conn.query(query01, ar2 -> {
        // query01 is not commited now
        conn.begin(ar3 -> {
            Transaction tx = ar3.result(); // begin is successfully scheduled to the server, query01 is committed
            // then we can do what we want
            tx.query(query02, ar4 -> {
                
            });
        });
    });
});
```
