### ISSUE TITLE
default the port number

### ISSUE THREAD

**Issue by gavinking** [eclipse-vertx/vertx-sql-client#660]
Currently it's necessary to explicitly specify port numbers with `ConnectOption`s, but every database has a default port, so the default port should be implied.

**Comment by vietj** [comment]
if you use `SqlConnectOptions` subclasses then you get the right port by default.

This class used to be abstract and user have to create the right subclass in order to get the proper default. A recent PR changed that and now we get this wrong default.

There is currently a discussion to add a "database product name" to `SqlConnectOptions`.

**Comment by gavinking** [comment]
Oh OK, so should I just close this issue then?

**Comment by vietj** [comment]
I think we keep it open for now

**Comment by gavinking** [comment]
@vietj is this issue still relevant?

**Comment by vietj** [comment]
I think it cannot be resolved so we can close it. Other ways to create options should be used.
