### ISSUE TITLE
Using custom socketFactory

### ISSUE THREAD

**Issue by jtama** [eclipse-vertx/vertx-sql-client#929]
# additional jdbc properties seems to be ignored.

Trying to specify additional jdbc properties in jdbc url connection string but they seemed to be ignore : 

### Version

Using 3.9.5

### Context

When specifying the following connection string : `postgresql:///my-db?cloudSqlInstance=project:europe-west1:my-db&socketFactory=com.google.cloud.sql.postgres.SocketFactory`, I get the following error : Connection refused: localhost/127.0.0.1:543

### Extra

The corresponding url with classical jdbc driver works perfectly fine. This is very needed to connect to GCP managed DB.

**Comment by vietj** [comment]
that will not be possible because vertx is based on Netty. You can connect on google cloud using domain sockets however.

**Comment by vietj** [comment]
here is an example with Vert.x : https://github.com/ludoch/samples/blob/master/java11/vertx-cloudsql-postgres/src/main/java/com/google/appengine/vertxcloudsqlpostgres/Application.java I think it could be adapted to work with Quarkus

**Comment by jtama** [comment]
Ok thanks I will check if I can make it work. And come back to you.

**Comment by jtama** [comment]
Ok I made it work thanks.

**Comment by spagop** [comment]
@jtama thanks for the prompt answer. to be sure, could you please confirm the guide you link work also with reactive sql clients (mysql)? because in one of your comment you mentioned that these configurations are needed:
%gcp.quarkus.datasource.reactive.url=postgresql://:5432/db-name?host=/cloudsql/project-id:zone:db-name    
%gcp.quarkus.vertx.prefer-native-transport=true
and with some netty dependencies. Please could please share a github project where you test the scenario?
