### ISSUE TITLE
Support load balancing across multiple hosts

### ISSUE THREAD

**Issue by vtumuluri** [eclipse-vertx/vertx-sql-client#98]
It would be great if this could support load balancing across read replicas which is supported in the official postgresql JDBC driver like below.
jdbc:postgresql://node1,node2,node3/accounting?targetServerType=preferSlave&loadBalanceHosts=true
Even if not by the same Uri parameters, any other mechanism to set multiple hosts that are load balanced for a specific pool is adequate.

**Comment by vietj** [comment]
@chinnitv I'm not much familiar with this feature, can you point out the doc to me ? is this something you could contribute ?

**Comment by chinnitv** [comment]
Here's the reference to the documentation https://jdbc.postgresql.org/documentation/head/connect.html
Sorry but I am a newbie to this project and even to vert.x. I am still trying to understand vert.x and may not be able to contribute any time soon.

**Comment by willks** [comment]
This is a good enhancement suggestion. I use both AWS RDS and GCP CloudSQL. I could have a look but need guidance around the DSL client setup.

**Comment by vietj** [comment]
I can provide you guidance

**Comment by BillyYccc** [comment]
Hi! I have done some investigation and there seems to be 2 features to deal with:
**Connection failover**: This is a **libpq** feature and is clearly defined in `33.1.1.3. Specifying Multiple Hosts` of https://www.postgresql.org/docs/current/libpq-connect.html.

It means pg client tries to connect to server with a list of nodes until one succeeds.

**Load balancing**: This is a **PgJDBC** feature https://jdbc.postgresql.org/documentation/head/connect.html and not stated in **libpq** documentation(I can't find this). 

PgJDBC uses two parameters here:
* loadBalanceHosts: use a random node choosing strategy to connect to server instead of one by one in order
* targetServerType: determine whether to connect to a master or a slave server(distinction is currently done by observing if the server allows writes).

So are we going to implement both of the two features?

Another doubt is how the `Multi-Host` feature applies in Pooling? Imagine we have a PgPool and configure 3 nodes:node1,node2,node3. Does the pool keep connections with all 3 nodes at the same time or sticks to only one address?

**Comment by vietj** [comment]
it would be good indeed first to clearly specifies such features and where they apply

**Comment by ThorKarlsson** [comment]
Is there any movement on this issue? I'd be interested in making a contribution.

**Comment by vietj** [comment]
@ThorKarlsson there are no plans, so you can contribute. If we can make this generic so that it applies to all client implementations it would be great too.

**Comment by vietj** [comment]
we will provide a function to dynamically provide connect options with a supplier, this could be used to achieve this easily I htink

**Comment by bachden** [comment]
> we will provide a function to dynamically provide connect options with a supplier, this could be used to achieve this easily I htink

is there any update (estimate/milestone...) for this?

**Comment by vietj** [comment]
we could achieve 4.1 I think, we are currently finishing the implementation of the new pool, so that would be an extra feature on top of this.

**Comment by alexpoletaev** [comment]
Good day everyone! Since this issue is closed I assume that this feature is implemented. @vietj, could you please provide an example how to implement load balancing between master and replica hosts with the vert.x reactive driver (in my case it's a postgres driver)? I need something similar, that is [implemented in the jdbc driver](https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java#L972) by default.

[Here](https://jdbc.postgresql.org/documentation/use/#connection-fail-over) is some info about postgres jdbc driver fail-over.

Example: one host (master) only for writes and one/multiple for reads (replicas). If master is down, then the replica will replace it in the infrastructure and vert.x driver should understand that it is available for writes now and use other replicas for reads.

Thanks in advance!

**Comment by vietj** [comment]
I think we don't implement this exact feature, what we do implement is load balancing against of list of postgres servers

we do have this issue open for 5.1 https://github.com/eclipse-vertx/vertx-sql-client/issues/1250

**Comment by alexpoletaev** [comment]
> I think we don't implement this exact feature, what we do implement is load balancing against of list of postgres servers
> 
> we do have this issue open for 5.1 #1250

Thank you! Asked another question in the provided issue
